<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!--定义相关机器人常量-->
    <xacro:property name="M_PI" value="3.1415926"/>
    <xacro:property name="base_radius" value="0.20"/>
    <xacro:property name="base_length" value="0.16"/>

    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_joint_y" value="0.19"/>
    <xacro:property name="wheel_joint_z" value="0.05"/>

    <xacro:property name="caster_radius" value="0.015"/> 
    <xacro:property name="caster_joint_x" value="0.18"/>
    <xacro:property name="camera_joint_x" value="0.17"/>
	<xacro:property name="camera_joint_z" value="0.10"/>
   <!--定义相关机器人颜色常量-->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    <!--定义驱动轮的宏定义--> 
    <!--prefix（左轮还是右轮） reflect（镜像关系）-->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="fixed">
            <origin xyz="0 ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}"  length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>
   <!--定义支撑轮的宏定义-->
   <!--prefix（前轮还是后轮） reflect（镜像关系）-->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="fixed">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(base_length/2 + caster_radius)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>
    <!--摄像头宏定义-->
	<xacro:macro name="camera" params="prefix reflect">
        <joint name="camera_joint" type="fixed">
            <origin xyz="${camera_joint_x} 0 ${camera_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="camera_link"/>
        </joint>

        <link name="camera_link">
            <visual>
	            <origin xyz=" 0 0 0 " rpy="0 0 0" />
	            <geometry>
	                <box size="0.03 0.04 0.04" />
	                   <!--外观是个盒子模拟成摄像头，长宽高分别是0.03 0.04 0.04-->
	            </geometry>
	            <material name="black"/>
	        </visual>
        </link>
    </xacro:macro>
    <!--定义主体base -->
        <xacro:macro name="mbot_base">  <!-- 宏定义 -->
        <link name="base_footprint">   <!-- 主要作用可以修改机器人主体的整体位置 -->
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

        <joint name="base_footprint_joint" type="fixed"><!-- 让机器人的base_link上移，至车轮与水平线平齐 -->
            <origin xyz="0 0 ${base_length/2 + caster_radius*2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${base_length}" radius="${base_radius}"/>
                </geometry>
                <material name="yellow" />
            </visual>
        </link>

        <wheel prefix="left" reflect="-1"/> <!-- 调用驱动轮子宏定义 -->
        <wheel prefix="right" reflect="1"/> <!-- 调用驱动轮子宏定义 -->

        <caster prefix="front" reflect="-1"/> <!-- 调用支撑轮子宏定义 -->
        <caster prefix="back" reflect="1"/> <!-- 调用支撑轮子宏定义 -->
        <camera/><!-- 调用摄像头宏定义 -->
    </xacro:macro>
</robot>

